name: Release Packages

on:
  workflow_run:
    workflows: ["Tag on Merge"]
    types:
      - completed

permissions:
  id-token: write
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: git fetch --tags

      - name: Find all new package tags on this commit
        id: find_tags
        run: |
          TAGS=$(git tag --points-at HEAD | grep -E '^@instructure.ai/.+@([0-9]+\.[0-9]+\.[0-9]+)$' || true)
          if [[ -z "$TAGS" ]]; then
            echo "No new matching tags found on this commit."
            exit 0
          fi
          # Save tags list for next steps
          echo "tags<<EOF" >> $GITHUB_ENV
          echo "$TAGS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Release each package tag
        if: env.tags != ''
        env:
          tags: ${{ env.tags }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail

          IFS=$'\n'
          for TAG in $tags; do
            PKG_NAME=$(echo "$TAG" | sed -E 's/@instructure.ai\/([^@]+)@.*/\1/')
            echo "Processing release for tag: $TAG (package: $PKG_NAME)"

            # Remove deprecated always-auth from .npmrc
            if [ -f "$HOME/.npmrc" ]; then
              sed -i.bak '/always-auth/d' "$HOME/.npmrc"
            fi

            # Install deps (no vite-node loader yet)
            npm install -g pnpm
            pnpm install --frozen-lockfile

            # NOW enable vite-node loader so any .ts/.mts imports work everywhere below
            export NODE_OPTIONS: --loader ${{ github.workspace }}/scripts/mts-loader.mjs

            # Build
            if [ "$PKG_NAME" = "shared-configs" ]; then
              echo "Skipping build for @instructure.ai/shared-configs."
            else
              echo "Building package: $PKG_NAME"
              pnpm build package "$PKG_NAME"
            fi

            # Test
            if [ "$PKG_NAME" = "shared-configs" ]; then
              echo "Skipping test for @instructure.ai/shared-configs."
            else
              pnpm -F "$PKG_NAME" test
            fi

            # Publish
            if [ "$PKG_NAME" = "shared-configs" ]; then
              echo "Skipping publish for @instructure.ai/shared-configs."
            else
              PKG_JSON_PATH="packages/$PKG_NAME/package.json"
              APP_JSON_PATH="apps/$PKG_NAME/package.json"
              if [ -f "$PKG_JSON_PATH" ]; then
                JSON_PATH="$PKG_JSON_PATH"
              elif [ -f "$APP_JSON_PATH" ]; then
                JSON_PATH="$APP_JSON_PATH"
              else
                JSON_PATH=""
              fi

              if [ -n "$JSON_PATH" ]; then
                ACCESS_PUBLIC=$(jq -r '.publishConfig.access' "$JSON_PATH")
                PRIVATE=$(jq -r '.private' "$JSON_PATH")
                if [ "$ACCESS_PUBLIC" = "public" ] && [ "$PRIVATE" != "true" ]; then
                  echo "Publishing $PKG_NAME as public..."
                  pnpm publish ./dist/*.tgz --access public
                elif [ "$PRIVATE" = "true" ]; then
                  echo "Skipping publish for $PKG_NAME because it is marked private in package.json."
                elif [ -n "$ACCESS_PUBLIC" ] && [ "$ACCESS_PUBLIC" != "public" ]; then
                  echo "Skipping publish for $PKG_NAME because publishConfig.access is set to '$ACCESS_PUBLIC' (not public)."
                else
                  echo "Publishing $PKG_NAME without --access public..."
                  pnpm publish ./dist/*.tgz
                fi
              else
                echo "package.json not found for $PKG_NAME in packages or apps, publishing without access check."
                pnpm publish ./dist/*.tgz
              fi
            fi

            # Create GitHub release using gh CLI
            if [ "$PKG_NAME" = "shared-configs" ]; then
              gh release create "$TAG" --title "$TAG" --generate-notes
            else
              gh release create "$TAG" ./dist/*.tgz --title "$TAG" --generate-notes
            fi
          done
