
name: Publish Package

on:
  push:
    tags:
      - '@instructure.ai/*@*.*.*'

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Remove deprecated always-auth from .npmrc
        run: |
          if [ -f "$NPM_CONFIG_USERCONFIG" ]; then
            sed -i.bak '/always-auth/d' "$NPM_CONFIG_USERCONFIG"
          fi
        env:
          NPM_CONFIG_USERCONFIG: $HOME/.npmrc
      - uses: actions/checkout@v4


      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies with pnpm
        run: pnpm install --frozen-lockfile

      - name: Extract package name
        id: pkgname
        run: echo "PKG_NAME=$(echo \"${GITHUB_REF_NAME}\" | sed -E 's/@instructure.ai\/([^@]+)@.*/\1/')" >> $GITHUB_ENV

      - name: Build
        run: |
          if [ "$PKG_NAME" = "shared-configs" ]; then
            echo "Skipping build for @instructure.ai/shared-configs."
          else
            echo "Building package: $PKG_NAME"
            pnpm build package "$PKG_NAME"
          fi

      - name: Test
        run: |
          if [ "$PKG_NAME" = "shared-configs" ]; then
            echo "Skipping test for @instructure.ai/shared-configs."
          else
            pnpm test
          fi

      - name: Publish package with pnpm
        run: |
          if [ "$PKG_NAME" = "shared-configs" ]; then
            echo "Skipping publish for @instructure.ai/shared-configs."
          else
            pnpm publish
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: ./dist/*.tgz
