name: Tag on Merge

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Tag changed packages and root
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for pkgjson in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^(package.json|packages/.*/package.json)$'); do
            NAME=$(jq -r .name $pkgjson)
            VERSION=$(jq -r .version $pkgjson)
            TAG="${NAME}@${VERSION}"
            git tag -f $TAG
            git push --force origin $TAG
          done