name: Validate PR Prefixes
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Validate PR source branch prefix
        shell: bash
        run: |
          BASE="${{ github.base_ref }}"
          HEAD="${{ github.head_ref }}"
          echo "Base: $BASE"
          echo "Head: $HEAD"

          # Gather package and app folder names
          PKGS=()
          if [ -d ./packages ]; then
            mapfile -t PKGDIRS < <(ls -1d ./packages/*/ 2>/dev/null | xargs -n 1 basename)
            PKGS+=("${PKGDIRS[@]}")
          fi
          if [ -d ./apps ]; then
            mapfile -t APPDIRS < <(ls -1d ./apps/*/ 2>/dev/null | xargs -n 1 basename)
            PKGS+=("${APPDIRS[@]}")
          fi
          echo "Package/app branches: ${PKGS[@]}"

          # If base is main, allow only main-* or <packagename>-* branches
          if [[ "$BASE" == "main" ]]; then
            for pkg in "${PKGS[@]}"; do
              if [[ "$HEAD" =~ ^"${pkg}-" ]]; then
                echo "✅ Allowed: PR from branch '$HEAD' (package prefix)"
                exit 0
              fi
            done
            if [[ "$HEAD" =~ ^"main-" ]]; then
              echo "✅ Allowed: PR from branch '$HEAD' (main- prefix)"
              exit 0
            fi
            echo "❌ Only PRs from branches starting with 'main-' or '<package>-' may target main."
            exit 1
          fi

          # If base is a package branch, allow only <packagename>-* branches
          for pkg in "${PKGS[@]}"; do
            if [[ "$BASE" == "$pkg" ]]; then
              if [[ "$HEAD" =~ ^"${pkg}-" ]]; then
                echo "✅ Allowed: PR from branch '$HEAD' (package prefix)"
                exit 0
              else
                echo "❌ PRs into '$BASE' must come from branches starting with '${BASE}-'"
                exit 1
              fi
            fi
          done

          echo "Base branch '$BASE' is not main or a package branch; skipping validation."
          exit 0
